// components/AIReviewGate.js
// Renders below any AI-generated output that may be used in proceedings.
// Blocks the primary action until the reviewer explicitly acknowledges advisory status.
import React, { useState } from 'react';
import {
  Box, Checkbox, FormControlLabel, Typography, TextField,
  Alert, Divider, Chip,
} from '@mui/material';
import { GppMaybe as GppMaybeIcon, VerifiedUser as VerifiedIcon } from '@mui/icons-material';

/**
 * AIReviewGate
 *
 * Props:
 *   onAcknowledged(reviewerName: string) — called when the user confirms review.
 *   acknowledged — boolean — controls whether gate is already confirmed (for parent state).
 *   requireName — boolean (default true) — whether the reviewer name field is mandatory.
 *   context — string — short label for what is being reviewed (e.g. "document analysis", "companion analysis").
 */
const AIReviewGate = ({ onAcknowledged, acknowledged, requireName = true, context = 'AI analysis' }) => {
  const [checked, setChecked] = useState(false);
  const [reviewerName, setReviewerName] = useState('');
  const [nameError, setNameError] = useState(false);

  const handleCheck = (e) => {
    const isChecked = e.target.checked;
    if (!isChecked) {
      setChecked(false);
      return;
    }
    if (requireName && !reviewerName.trim()) {
      setNameError(true);
      return;
    }
    setNameError(false);
    setChecked(true);
    onAcknowledged(reviewerName.trim() || 'Unnamed reviewer');
  };

  const handleNameChange = (e) => {
    setReviewerName(e.target.value);
    if (e.target.value.trim()) setNameError(false);
  };

  if (acknowledged) {
    return (
      <Box sx={{ mt: 1.5 }}>
        <Divider sx={{ mb: 1.5 }} />
        <Chip
          icon={<VerifiedIcon />}
          label={`Advisory status acknowledged${reviewerName ? ` — ${reviewerName}` : ''}`}
          color="success"
          size="small"
          variant="outlined"
        />
      </Box>
    );
  }

  return (
    <Box sx={{ mt: 2 }}>
      <Divider sx={{ mb: 2 }} />
      <Alert
        severity="warning"
        icon={<GppMaybeIcon />}
        sx={{ mb: 2 }}
      >
        <Typography variant="body2" fontWeight="medium" gutterBottom>
          Human Review Required Before Use in Proceedings
        </Typography>
        <Typography variant="body2">
          This {context} is generated by AI and is <strong>advisory only</strong>. It must be
          verified against primary legal sources by a qualified legal professional before being
          relied upon in any arbitration proceeding, submission, or procedural decision.
          AI outputs may contain errors, omissions, or hallucinated citations.
        </Typography>
      </Alert>

      {requireName && (
        <TextField
          label="Reviewing counsel / arbitrator name"
          size="small"
          fullWidth
          value={reviewerName}
          onChange={handleNameChange}
          error={nameError}
          helperText={nameError ? 'Please enter your name before acknowledging.' : 'Name is recorded for audit purposes.'}
          sx={{ mb: 1.5 }}
        />
      )}

      <FormControlLabel
        control={
          <Checkbox
            checked={checked}
            onChange={handleCheck}
            color="warning"
          />
        }
        label={
          <Typography variant="body2">
            I confirm I have reviewed this {context} against primary legal sources and verified
            it is accurate and appropriate for use in these proceedings. I understand I bear
            sole professional responsibility for any reliance placed on this output.
          </Typography>
        }
      />
    </Box>
  );
};

export default AIReviewGate;
