const RULE_PRESETS = {
  'Arbitration Act (Cap. 49)': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will be conducted under the Arbitration Act, Cap. 49, together with any case-specific directions agreed by the parties and issued by the tribunal.',
    tribunalDetails: 'The tribunal will be constituted as agreed by the parties and may consist of one or more arbitrators as recorded in the case setup.',
    procedure: 'The tribunal may manage the process flexibly, including timetables, written submissions, directions, and hearing format, while keeping the process fair and efficient.',
    evidenceHearings: 'Evidence, witness handling, and hearing dates will follow tribunal directions. Hearings may be virtual or in person depending on the parties’ agreement and practical needs.',
    powers: 'The arbitrator may issue procedural orders, manage deadlines, determine admissibility, and take other steps allowed by the Act.',
    costs: 'Costs, fees, and expenses may be allocated by agreement or in the final award, subject to the tribunal’s directions and applicable law.',
    enforcement: 'Any award may be enforced according to the Arbitration Act, Cap. 49 and the rules of the relevant court of competent jurisdiction.',
    notes: 'Ad hoc arbitration framework under Kenyan law.',
  },
  'NCIA Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the NCIA Rules together with the Arbitration Act, Cap. 49, and any administrative directions issued for the case.',
    tribunalDetails: 'The tribunal will be constituted under the NCIA procedure, including any institution-assisted appointment or confirmation steps recorded for the case.',
    procedure: 'NCIA case management may govern filing, service, timetable control, and procedural directions. The tribunal should keep the process efficient and orderly.',
    evidenceHearings: 'The tribunal may direct documentary exchange, witness handling, hearing logistics, and remote or in-person sessions according to the NCIA framework.',
    powers: 'The arbitrator may issue case-management directions and procedural orders consistent with the NCIA Rules and the Act.',
    costs: 'Costs and administrative fees may be dealt with under the NCIA framework and ultimately reflected in the award or a tribunal direction.',
    enforcement: 'Awards remain enforceable under the Arbitration Act, Cap. 49 and any applicable enforcement process.',
    notes: 'Institutional arbitration with NCIA case management support.',
  },
  'KIAC Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the KIAC Rules together with the Arbitration Act, Cap. 49, and any tribunal directions.',
    tribunalDetails: 'Tribunal appointment and administration should follow the KIAC framework recorded for the case.',
    procedure: 'KIAC procedure typically supports case management, filing timelines, and tribunal supervision of pleadings and hearings.',
    evidenceHearings: 'Document exchange, witness evidence, and hearing dates should follow tribunal directions and KIAC administration where applicable.',
    powers: 'The arbitrator may issue procedural directions, manage evidence, and keep the case on schedule under the institutional rules.',
    costs: 'Costs should be allocated in line with the KIAC framework and the final award or directions.',
    enforcement: 'Any award remains subject to enforcement under the applicable arbitration law and court process.',
    notes: 'Institutional arbitration with KIAC case administration.',
  },
  'LCIA Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the LCIA Rules and the Arbitration Act, Cap. 49, with any seat-specific procedural requirements also applying.',
    tribunalDetails: 'The tribunal structure, appointment steps, and procedural administration should align with the LCIA framework selected for the case.',
    procedure: 'LCIA proceedings generally rely on case management, written directions, and tribunal control of timetable and hearing format.',
    evidenceHearings: 'The tribunal may direct witness handling, evidence exchange, and hearing logistics according to the LCIA framework.',
    powers: 'The arbitrator may issue procedural orders and manage the case consistently with the LCIA Rules.',
    costs: 'Costs and fees are typically managed under the LCIA cost framework and the tribunal’s eventual allocation.',
    enforcement: 'Awards may be enforced under the applicable law of the seat and relevant court process.',
    notes: 'International institutional arbitration under LCIA procedures.',
  },
  'ICC Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the ICC Rules and the Arbitration Act, Cap. 49, with any case-specific procedural orders from the tribunal.',
    tribunalDetails: 'Tribunal constitution and administration should follow the ICC case framework selected for the dispute.',
    procedure: 'ICC proceedings often include structured case management, directions, and a controlled schedule for submissions and hearings.',
    evidenceHearings: 'The tribunal may organize written evidence, hearing format, and witness examination according to ICC case management.',
    powers: 'The arbitrator may issue directions and manage the proceeding in line with the ICC Rules.',
    costs: 'Costs, administrative fees, and tribunal fees should be handled under the ICC framework and final award allocation.',
    enforcement: 'Awards are enforced under the relevant seat law and enforcement rules.',
    notes: 'International institutional arbitration under ICC procedures.',
  },
  'SIAC Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the SIAC Rules together with the Arbitration Act, Cap. 49, and any tribunal orders.',
    tribunalDetails: 'Tribunal appointment and case administration should align with the SIAC framework chosen by the parties.',
    procedure: 'SIAC proceedings typically emphasize efficient case management, defined deadlines, and tribunal supervision of submissions and hearings.',
    evidenceHearings: 'The tribunal may direct evidence exchange, witness handling, and hearing structure under the SIAC framework.',
    powers: 'The arbitrator may issue procedural directions and manage the dispute under the SIAC Rules.',
    costs: 'Costs and fees should be allocated under the SIAC framework and reflected in the award or directions.',
    enforcement: 'Awards remain enforceable under the law of the seat and applicable court process.',
    notes: 'International institutional arbitration under SIAC procedures.',
  },
  'UNCITRAL Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the UNCITRAL Rules and the Arbitration Act, Cap. 49, unless the parties agree otherwise in writing.',
    tribunalDetails: 'The tribunal should be formed according to the parties’ agreement and any appointment method selected under the UNCITRAL framework.',
    procedure: 'UNCITRAL proceedings usually rely on a party-agreed, tribunal-managed process with written submissions and fair hearing rights.',
    evidenceHearings: 'The tribunal may decide how evidence is exchanged and how hearings are held under the chosen procedural framework.',
    powers: 'The arbitrator may issue directions, manage the timetable, and make procedural decisions under the UNCITRAL framework.',
    costs: 'Costs are commonly allocated by agreement or by the award, subject to the tribunal’s procedural rulings.',
    enforcement: 'Any award is enforced under the applicable law at the seat and through the relevant court process.',
    notes: 'Ad hoc style arbitration using the UNCITRAL procedural framework.',
  },
  'AAA Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the AAA Rules and the Arbitration Act, Cap. 49, with any procedural directions needed for the case.',
    tribunalDetails: 'Tribunal appointment and administration should follow the AAA framework chosen for the dispute.',
    procedure: 'AAA proceedings generally rely on structured case management, defined submissions, and tribunal control of the process.',
    evidenceHearings: 'The tribunal may manage evidence, witness examination, and hearings under the AAA framework.',
    powers: 'The arbitrator may issue procedural orders and keep the matter moving under the AAA Rules.',
    costs: 'Costs and fees should be allocated under the AAA framework and the award or directions of the tribunal.',
    enforcement: 'Awards are enforced according to the law of the seat and applicable court process.',
    notes: 'Institutional arbitration under AAA procedures.',
  },
  'AFSA Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the AFSA Rules and the Arbitration Act, Cap. 49, with tribunal directions applied as needed.',
    tribunalDetails: 'Tribunal appointment and management should follow the AFSA framework selected for the case.',
    procedure: 'AFSA procedure generally includes structured case management, service, and hearing control by the tribunal.',
    evidenceHearings: 'The tribunal may direct disclosure, witness evidence, and hearing format under the AFSA framework.',
    powers: 'The arbitrator may issue directions and procedural orders under the AFSA Rules.',
    costs: 'Costs and fees should be addressed under the AFSA framework and in the final award.',
    enforcement: 'Awards remain enforceable under the seat law and relevant court process.',
    notes: 'Institutional arbitration under AFSA procedures.',
  },
  'LCA Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the LCA Rules and the Arbitration Act, Cap. 49, together with any tribunal directions.',
    tribunalDetails: 'The tribunal should be constituted and administered according to the selected LCA framework.',
    procedure: 'LCA proceedings generally use tribunal-managed timelines, written submissions, and hearing directions.',
    evidenceHearings: 'Evidence exchange, witness handling, and hearing logistics are managed by the tribunal under the LCA framework.',
    powers: 'The arbitrator may issue directions and manage the case under the LCA Rules.',
    costs: 'Costs and fees should be allocated by the tribunal or under the LCA framework.',
    enforcement: 'Awards are enforceable under the law of the seat and relevant enforcement procedures.',
    notes: 'Institutional arbitration under LCA procedures.',
  },
  'CRCICA Rules': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed under the CRCICA Rules and the Arbitration Act, Cap. 49, with any tribunal directions and institutional procedures applied.',
    tribunalDetails: 'Tribunal appointment and administration should follow the CRCICA framework selected for the case.',
    procedure: 'CRCICA proceedings normally include tribunal supervision of submissions, hearings, and timetable management.',
    evidenceHearings: 'The tribunal may decide evidence exchange and hearing format in line with the CRCICA framework.',
    powers: 'The arbitrator may issue procedural orders and manage the dispute under the CRCICA Rules.',
    costs: 'Costs and fees should be dealt with under the CRCICA framework and the final award.',
    enforcement: 'Awards remain enforceable under the applicable seat law and court process.',
    notes: 'Institutional arbitration under CRCICA procedures.',
  },
  'Ad Hoc': {
    governingLaw: 'Arbitration Act, Cap. 49',
    governingRulesText: 'The arbitration will proceed as an ad hoc arbitration under the Arbitration Act, Cap. 49, with the parties and tribunal agreeing the procedure in writing.',
    tribunalDetails: 'The tribunal will be constituted as agreed by the parties, with any appointment process recorded in the case file.',
    procedure: 'The parties and tribunal should agree the timetable, filings, evidence handling, and hearing method directly, subject to the Act.',
    evidenceHearings: 'Evidence exchange, witness evidence, and hearing format should be set by the tribunal or the parties by agreement.',
    powers: 'The arbitrator may issue procedural directions and manage the case in a fair and efficient manner under the Act.',
    costs: 'Costs and fees should be agreed by the parties or determined in the final award.',
    enforcement: 'Any award may be enforced according to the Arbitration Act, Cap. 49 and the relevant court process.',
    notes: 'Party-managed ad hoc arbitration under Kenyan law.',
  },
};

export const getRulePreset = (ruleName) => {
  const key = String(ruleName || '').trim();
  return RULE_PRESETS[key] || null;
};

export const listRulePresetNames = () => Object.keys(RULE_PRESETS);

